sudo: false

language:
  - php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.6
  - hhvm
  - 7.0
  - 7.1

dist: trusty

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
  include:
    - php: 5.6
      env: SYMFONY_VERSION='2.8.*'
    - php: 5.6
      env: SYMFONY_VERSION='3.0.*'
    - php: 5.6
      env: SYMFONY_VERSION='3.2.*'
    - php: 5.6
      env: SYMFONY_VERSION='3.3.*'
    - php: 7.0
      env: SYMFONY_VERSION='2.8.*'
    - php: 7.0
      env: SYMFONY_VERSION='3.0.*'
    - php: 7.0
      env: SYMFONY_VERSION='3.2.*'
    - php: 7.0
      env: SYMFONY_VERSION='3.3.*'
    - php: 7.1
      env: SYMFONY_VERSION='4.0.*'

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "5.6" && "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/framework-bundle:${SYMFONY_VERSION}; fi

install: composer update $COMPOSER_FLAGS --dev --no-interaction --prefer-dist

script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then mkdir -p build/logs; fi
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit; fi

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then php vendor/bin/coveralls -v; fi
