language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  matrix:
    - SYMFONY_REQUIRE="3.4.*"
    - SYMFONY_REQUIRE="4.4.*"
    - SYMFONY_REQUIRE="5.0.*"

matrix:
  fast_finish: true
  exclude:
    - php: 7.1
      env: SYMFONY_REQUIRE="5.0.*"

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available";
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
  - composer self-update
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex

install:
  - composer install --prefer-dist --no-interaction --no-scripts

script:
  - make ci
